spring:
  application:
    name: Horta Connect API

  datasource:
    # Conex√£o com o banco 'hortaconnect' (Crie esse banco no MySQL antes!)
    url: jdbc:mysql://localhost:3306/hortaconnect?useTimezone=true&serverTimezone=UTC

    # Seu usu√°rio (geralmente √© root)
    username: root

    # üëá AQUI EST√Å A M√ÅGICA: Ele vai buscar a senha na vari√°vel de ambiente
    password: ${DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # "update": Se a tabela n√£o existir, ele cria. Se mudar algo no Java, ele atualiza no banco.
    hibernate:
      ddl-auto: update

    # Mostra o SQL no console (√ìtimo para voc√™ ver o que est√° acontecendo)
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect